# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3a8dda1bd508628aae0b4770b47123a2f2df999391997750df214332424b8665022bf11767fca78dc24212b02878d3bad23f8b8d7e9f20b0d54adde35bf1ac6

test:
  secret_key_base: 11f0861573038cec44274ea4fca7be5aa5ee209d344dbedc3f44e5734fa3785b0599789f415b608b3f60eb5388cfd4a10c4581986025de43c2c67f91bc3172eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
